# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
title                    : "Kunze Wang"
title_separator          : "-"
name                     : &name "Your Name"
description              : &description "personal description"
url                      : https://matrixblake.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "academicpages/academicpages.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "profile.png"
  name             : "Kunze Wang"
  pronouns         : # example: "she/her"  
  bio              : "PhD in NLP from USYD | Machine Learning Engineer @ ROKT"
  location         : "Sydney"
  employer         : "ROKT"
  uri              : # URL
  email            : "blakewkz[AT]gmail.com" 

  # Academic websites
  arxiv            : # URL - Update with the correct link to your profile
  googlescholar    : "https://scholar.google.com.au/citations?user=Df_a3YQAAAAJ&hl=en"
  impactstory      : # URL
  orcid            : "https://orcid.org/0000-0003-3393-2181"
  semantic         : # URL
  pubmed           : # URL "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  researchgate     : # URL

  # Repositories and software development
  bitbucket        : # Username - Update